// app/api/live/response/route.ts
// StayKnown Upgrade Master File Record
//
// NEW FILE
//
// Signed LIVE-map gateway for the EXISTING authoritative exceeded-Visit
// selected-contact response flow.
//
// Authority boundary:
//   app/api/live/response/route.ts
//     -> public.sk_upsert_visit_time_contact_response(...)
//
// This route does not create another response table or reinterpret the meaning
// of Checking, Reached them, or Can’t reach. The existing RPC remains
// authoritative for deadline validation, selected-contact validation,
// idempotency, current-response state, and immutable response history.
//
// The website route additionally:
// - revalidates the signed v2 recipient-bound LIVE access;
// - verifies the recorded LIVE-map safety-use consent;
// - verifies the exact response opportunity generated by the status route;
// - resolves the selected contact to a real StayKnown user account;
// - records privacy-safe audit metadata;
// - creates the owner’s existing in-app/push projection only after the RPC
//   reports that the authoritative response changed;
// - never treats a participant response as independent proof of safety;
// - never changes, ends, extends, pauses, or stops the Visit;
// - never starts or stops SOS;
// - never stores raw signing tokens, IP addresses, user-agent strings,
//   coordinates, device identifiers, or account credentials.

import { createHmac, timingSafeEqual } from "node:crypto";

import { NextResponse } from "next/server";
import type { SupabaseClient } from "@supabase/supabase-js";

import type {
  LiveDeliveryHealth,
  LiveResponseAction,
  LiveResponseResponse,
} from "../../../live/live-types";
import {
  accessFromUnknown,
  canUseInteractiveLiveActions,
  clean,
  createAdminClient,
  requestIpHash,
  resolveStayKnownUserByEmail,
  validateVisitAccess,
  verifyLiveAccess,
  visitHasEnded,
  visitOwnerUserId,
} from "../../../live/live-access";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

const POLICY_VERSION = "visit-map-safety-use-v2-2026-07-17";
const RESPONSE_PROFILE = "visit_time_contact_response";
const PUSH_TIMEOUT_MS = 12000;
const INTELLIGENCE_TIMEOUT_MS = 5000;

const RESPONSE_HEADERS: Record<string, string> = {
  "Cache-Control": "private, no-store, no-cache, must-revalidate, max-age=0",
  Pragma: "no-cache",
  Expires: "0",
  "Cross-Origin-Resource-Policy": "same-origin",
  "Referrer-Policy": "no-referrer",
  "X-Content-Type-Options": "nosniff",
  "X-Robots-Tag": "noindex, nofollow, noarchive, nosnippet",
};

type JsonObject = Record<string, unknown>;

type TimingRow = {
  visit_id?: string | null;
  owner_user_id?: string | null;
  deadline_version?: number | string | null;
  expected_end_at?: string | null;
  status?: string | null;
  selected_contact_ids?: unknown;
  first_overdue_at?: string | null;
  last_overdue_at?: string | null;
  metadata?: unknown;
  [key: string]: unknown;
};

type ContactRow = {
  id?: string | null;
  user_id?: string | null;
  name?: string | null;
  alias?: string | null;
  email?: string | null;
  target_user_id?: string | null;
  approval_status?: string | null;
  blocked?: boolean | null;
  restricted?: boolean | null;
  [key: string]: unknown;
};

type ResponderIdentity = {
  userId: string;
  displayName: string;
  email: string;
  avatarUrl: string;
  verified: boolean;
  badgeType: string;
  badgeStatus: string;
};

type ResponseCopy = {
  label: string;
  title: string;
  body: string;
  notificationKind: string;
  confirmation: string;
  severity: "info" | "warning";
};

type RpcResponse = {
  id?: string | null;
  visit_id?: string | null;
  owner_user_id?: string | null;
  deadline_version?: number | string | null;
  responder_user_id?: string | null;
  recipient_contact_id?: string | null;
  response_kind?: string | null;
  status?: string | null;
  first_responded_at?: string | null;
  responded_at?: string | null;
  updated_at?: string | null;
  [key: string]: unknown;
};

type RpcEnvelope = {
  ok?: boolean;
  changed?: boolean;
  already_recorded?: boolean;
  response?: RpcResponse | null;
  [key: string]: unknown;
};

type DeliveryProjection = {
  notificationRecorded: boolean;
  pushDelivered: boolean;
  pushCode: string;
  timelineRecorded: boolean;
  deliveryHealthRecorded: boolean;
  intelligenceRequested: boolean;
};

type RouteSuccess = LiveResponseResponse & {
  changed: boolean;
  already_recorded: boolean;
  label: string;
  message: string;
  authority: "sk_upsert_visit_time_contact_response";
  response_profile: typeof RESPONSE_PROFILE;
  delivery: {
    notification_recorded: boolean;
    push_delivered: boolean;
    timeline_recorded: boolean;
  };
};

function jsonResponse(
  body: Record<string, unknown>,
  status = 200,
  extraHeaders: Record<string, string> = {},
): NextResponse {
  return NextResponse.json(body, {
    status,
    headers: {
      ...RESPONSE_HEADERS,
      ...extraHeaders,
    },
  });
}

function asObject(value: unknown): JsonObject {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as JsonObject)
    : {};
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];

  return Array.from(new Set(value.map((item) => clean(item)).filter(Boolean)));
}

function finiteInteger(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) {
    return Number.isSafeInteger(Math.trunc(value)) ? Math.trunc(value) : null;
  }

  const parsed = Number(clean(value));

  if (!Number.isFinite(parsed)) return null;

  const integer = Math.trunc(parsed);

  return Number.isSafeInteger(integer) ? integer : null;
}

function isUuid(value: unknown): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
    clean(value),
  );
}

function dateMilliseconds(value: unknown): number | null {
  const raw = clean(value);

  if (!raw) return null;

  const date = new Date(raw);
  const milliseconds = date.getTime();

  return Number.isNaN(milliseconds) ? null : milliseconds;
}

function contentTypeIsJson(req: Request): boolean {
  return clean(req.headers.get("content-type"))
    .toLowerCase()
    .includes("application/json");
}

function configuredSiteOrigin(): string {
  const raw = clean(
    process.env.NEXT_PUBLIC_SITE_URL ??
      process.env.SITE_URL ??
      "https://www.stay-known.com",
  );

  try {
    return new URL(raw).origin;
  } catch {
    return "https://www.stay-known.com";
  }
}

function allowedOrigins(req: Request): Set<string> {
  const origins = new Set<string>();

  try {
    origins.add(new URL(req.url).origin);
  } catch {}

  origins.add(configuredSiteOrigin());

  return origins;
}

function requestIsSameOrigin(req: Request): boolean {
  const allowed = allowedOrigins(req);
  const fetchSite = clean(req.headers.get("sec-fetch-site")).toLowerCase();

  if (fetchSite === "cross-site" || fetchSite === "none") {
    return false;
  }

  const origin = clean(req.headers.get("origin"));

  if (origin && !allowed.has(origin)) {
    return false;
  }

  const referer = clean(req.headers.get("referer"));

  if (referer) {
    try {
      if (!allowed.has(new URL(referer).origin)) {
        return false;
      }
    } catch {
      return false;
    }
  }

  return Boolean(
    origin ||
    referer ||
    fetchSite === "same-origin" ||
    fetchSite === "same-site",
  );
}

function normalizeResponseAction(value: unknown): LiveResponseAction | null {
  const normalized = clean(value)
    .toLowerCase()
    .replaceAll("’", "'")
    .replaceAll("-", "_")
    .replaceAll(" ", "_");

  switch (normalized) {
    case "checking":
    case "visit_time_checking":
    case "sk_visit_time_checking":
      return "checking";

    case "reached":
    case "reached_them":
    case "visit_time_reached":
    case "sk_visit_time_reached":
      return "reached";

    case "cannot_reach":
    case "cant_reach":
    case "can't_reach":
    case "unable_to_reach":
    case "visit_time_cannot_reach":
    case "sk_visit_time_cannot_reach":
      return "cannot_reach";

    default:
      return null;
  }
}

function responseCopy(
  action: LiveResponseAction,
  responderName: string,
): ResponseCopy {
  switch (action) {
    case "checking":
      return {
        label: "Checking",
        title: "A Visit contact is checking",
        body:
          `${responderName} selected Checking for your exceeded Visit. ` +
          "They may contact you directly to confirm you are safe.",
        notificationKind: "visit_time_contact_checking",
        confirmation: "Checking was shared with the Visit owner.",
        severity: "info",
      };

    case "reached":
      return {
        label: "Reached them",
        title: "Your Visit contact reached you",
        body: `${responderName} selected Reached them for your exceeded Visit.`,
        notificationKind: "visit_time_contact_reached",
        confirmation: "Reached them was shared with the Visit owner.",
        severity: "info",
      };

    case "cannot_reach":
      return {
        label: "Can’t reach",
        title: "A Visit contact can’t reach you",
        body:
          `${responderName} selected Can’t reach for your exceeded Visit. ` +
          "Open StayKnown and update or end the Visit as soon as you safely can.",
        notificationKind: "visit_time_contact_cannot_reach",
        confirmation: "Can’t reach was shared with the Visit owner.",
        severity: "warning",
      };
  }
}

function opportunityId(params: {
  visitId: string;
  recipientContactId: string;
  deadlineVersion: number;
}): string {
  const secret = clean(
    process.env.LIVE_AUDIT_HASH_SECRET ??
      process.env.INTERNAL_EVENT_SECRET ??
      process.env.TRACKING_SIGNING_SECRET,
  );

  const material =
    `${params.visitId}:` +
    `${params.recipientContactId}:` +
    `${params.deadlineVersion}`;

  if (!secret) {
    return `visit-response-${params.deadlineVersion}`;
  }

  const digest = createHmac("sha256", secret)
    .update(`stayknown-live-response:${material}`, "utf8")
    .digest("base64url")
    .slice(0, 40);

  return `visit-response-${digest}`;
}

function safeEqualText(leftValue: string, rightValue: string): boolean {
  const left = Buffer.from(leftValue, "utf8");
  const right = Buffer.from(rightValue, "utf8");

  if (left.length !== right.length) return false;

  try {
    return timingSafeEqual(left, right);
  } catch {
    return false;
  }
}

function userAgentSummary(req: Request): JsonObject {
  const userAgent = clean(req.headers.get("user-agent")).slice(0, 1000);

  if (!userAgent) {
    return {
      available: false,
      raw_user_agent_stored: false,
    };
  }

  const normalized = userAgent.toLowerCase();

  const platform = normalized.includes("android")
    ? "android"
    : normalized.includes("iphone") ||
        normalized.includes("ipad") ||
        normalized.includes("ios")
      ? "ios"
      : normalized.includes("windows")
        ? "windows"
        : normalized.includes("macintosh") || normalized.includes("mac os")
          ? "macos"
          : normalized.includes("linux")
            ? "linux"
            : "unknown";

  const browser = normalized.includes("edg/")
    ? "edge"
    : normalized.includes("chrome/")
      ? "chrome"
      : normalized.includes("safari/") && !normalized.includes("chrome/")
        ? "safari"
        : normalized.includes("firefox/")
          ? "firefox"
          : "unknown";

  const secret = clean(
    process.env.LIVE_AUDIT_HASH_SECRET ??
      process.env.INTERNAL_EVENT_SECRET ??
      process.env.TRACKING_SIGNING_SECRET,
  );

  const userAgentHash = secret
    ? createHmac("sha256", secret)
        .update(`stayknown-live-response-client:${userAgent}`, "utf8")
        .digest("hex")
    : "";

  return {
    available: true,
    platform,
    browser,
    ...(userAgentHash ? { user_agent_hash: userAgentHash } : {}),
    raw_user_agent_stored: false,
  };
}

function configuredStorageOrigin(): string {
  const raw = clean(
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL,
  );

  if (!raw) return "";

  try {
    return new URL(raw).origin;
  } catch {
    return "";
  }
}

function safeAbsoluteAvatarUrl(raw: string): string {
  if (!raw) return "";

  try {
    const url = new URL(raw);

    if (url.protocol !== "https:") return "";

    const allowedOrigin = configuredStorageOrigin();

    if (allowedOrigin && url.origin !== allowedOrigin) {
      return "";
    }

    return url.toString();
  } catch {
    return "";
  }
}

function logDatabaseFailure(operation: string, error: unknown): void {
  const row = asObject(error);

  console.error(`[SK_LIVE_RESPONSE] ${operation} failed`, {
    code: clean(row.code) || null,
    message:
      clean(row.message) ||
      (error instanceof Error ? error.message : "unknown_error"),
    details: clean(row.details) || null,
    hint: clean(row.hint) || null,
  });
}

function backendObjectMissing(error: unknown): boolean {
  const row = asObject(error);
  const code = clean(row.code).toUpperCase();
  const message = [
    clean(row.message),
    clean(row.details),
    clean(row.hint),
    error instanceof Error ? error.message : "",
  ]
    .join(" ")
    .toLowerCase();

  return (
    code === "42P01" ||
    code === "42703" ||
    code === "42883" ||
    code === "PGRST202" ||
    code === "PGRST204" ||
    code === "PGRST205" ||
    message.includes("does not exist") ||
    message.includes("could not find the table") ||
    message.includes("could not find the function") ||
    message.includes("schema cache")
  );
}

async function signedAvatar(
  admin: SupabaseClient,
  rawPath: string,
): Promise<string> {
  const raw = clean(rawPath);

  if (!raw) return "";

  if (/^https?:\/\//i.test(raw)) {
    return safeAbsoluteAvatarUrl(raw);
  }

  const normalized = raw.replace(/^\/+/, "");

  const candidates = normalized.startsWith("avatars/")
    ? [{ bucket: "avatars", path: normalized.slice("avatars/".length) }]
    : normalized.startsWith("safety-gallery/")
      ? [
          {
            bucket: "safety-gallery",
            path: normalized.slice("safety-gallery/".length),
          },
        ]
      : [
          { bucket: "avatars", path: normalized },
          { bucket: "safety-gallery", path: normalized },
        ];

  for (const candidate of candidates) {
    if (!candidate.path) continue;

    try {
      const result = await admin.storage
        .from(candidate.bucket)
        .createSignedUrl(candidate.path, 60 * 30);

      if (result.error) {
        logDatabaseFailure(
          `avatar signing (${candidate.bucket})`,
          result.error,
        );
        continue;
      }

      const url = safeAbsoluteAvatarUrl(clean(result.data?.signedUrl));

      if (url) return url;
    } catch (error) {
      logDatabaseFailure(`avatar signing (${candidate.bucket})`, error);
    }
  }

  return "";
}

async function loadResponderIdentity(
  admin: SupabaseClient,
  params: {
    responderUserId: string;
    contact: ContactRow;
  },
): Promise<ResponderIdentity> {
  const contactEmail = clean(params.contact.email).toLowerCase();
  const contactName =
    clean(params.contact.name) ||
    clean(params.contact.alias) ||
    contactEmail.split("@")[0] ||
    "A Visit contact";

  let displayName = contactName;
  let email = contactEmail;
  let avatarPath = "";
  let verified = false;
  let badgeType = "";
  let badgeStatus = "";

  const [profileResult, userProfileResult, badgeResult] = await Promise.all([
    admin
      .from("profiles")
      .select("first_name,last_name,email,avatar_url,verified")
      .eq("id", params.responderUserId)
      .maybeSingle(),
    admin
      .from("user_profile")
      .select("display_name,first_name,last_name,email,profile_photo_url")
      .eq("user_id", params.responderUserId)
      .maybeSingle(),
    admin
      .from("user_verification_badges")
      .select("badge_type,status,awarded_at,created_at")
      .eq("user_id", params.responderUserId)
      .eq("status", "active")
      .is("removed_at", null)
      .order("awarded_at", { ascending: false })
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
  ]);

  if (profileResult.error) {
    logDatabaseFailure("responder profiles lookup", profileResult.error);
  }

  if (userProfileResult.error) {
    logDatabaseFailure(
      "responder user_profile lookup",
      userProfileResult.error,
    );
  }

  if (badgeResult.error) {
    logDatabaseFailure(
      "responder verification badge lookup",
      badgeResult.error,
    );
  }

  const profile = asObject(profileResult.data);
  const userProfile = asObject(userProfileResult.data);

  const firstName = clean(userProfile.first_name) || clean(profile.first_name);
  const lastName = clean(userProfile.last_name) || clean(profile.last_name);

  displayName =
    clean(userProfile.display_name) ||
    [firstName, lastName].filter(Boolean).join(" ") ||
    displayName;

  email =
    clean(userProfile.email).toLowerCase() ||
    clean(profile.email).toLowerCase() ||
    email;

  avatarPath =
    clean(userProfile.profile_photo_url) || clean(profile.avatar_url);

  verified = profile.verified === true || Boolean(badgeResult.data);

  badgeType = clean(badgeResult.data?.badge_type);
  badgeStatus = clean(badgeResult.data?.status);

  return {
    userId: params.responderUserId,
    displayName,
    email,
    avatarUrl: await signedAvatar(admin, avatarPath),
    verified,
    badgeType,
    badgeStatus,
  };
}

async function loadTiming(
  admin: SupabaseClient,
  visitId: string,
): Promise<TimingRow> {
  const result = await admin
    .from("visit_time_expectations")
    .select("*")
    .eq("visit_id", visitId)
    .maybeSingle();

  if (result.error) {
    logDatabaseFailure("Visit timing lookup", result.error);

    if (backendObjectMissing(result.error)) {
      throw new Error("response_authority_unavailable");
    }

    throw new Error("timing_lookup_failed");
  }

  if (!result.data) {
    throw new Error("timing_not_found");
  }

  return result.data as TimingRow;
}

function validateTiming(params: {
  timing: TimingRow;
  visitId: string;
  ownerUserId: string;
  recipientContactId: string;
}): number {
  const timingVisitId = clean(params.timing.visit_id);
  const timingOwnerId = clean(params.timing.owner_user_id);
  const deadlineVersion = finiteInteger(params.timing.deadline_version) ?? 0;

  if (
    timingVisitId !== params.visitId ||
    timingOwnerId !== params.ownerUserId
  ) {
    throw new Error("timing_subject_mismatch");
  }

  if (deadlineVersion < 1) {
    throw new Error("timing_not_ready");
  }

  const selectedContactIds = asStringArray(params.timing.selected_contact_ids);

  if (!selectedContactIds.includes(params.recipientContactId)) {
    throw new Error("recipient_not_selected");
  }

  const timingStatus = clean(params.timing.status).toLowerCase();

  if (timingStatus && !["active", "extended"].includes(timingStatus)) {
    throw new Error("response_opportunity_closed");
  }

  const expectedEndAt = dateMilliseconds(params.timing.expected_end_at);

  const overdue =
    Boolean(clean(params.timing.first_overdue_at)) ||
    Boolean(clean(params.timing.last_overdue_at)) ||
    (expectedEndAt != null && expectedEndAt <= Date.now());

  if (!overdue) {
    throw new Error("response_opportunity_not_open");
  }

  return deadlineVersion;
}

async function loadSelectedContact(
  admin: SupabaseClient,
  params: {
    ownerUserId: string;
    recipientContactId: string;
    selectedContactIds: string[];
  },
): Promise<ContactRow> {
  if (!params.selectedContactIds.includes(params.recipientContactId)) {
    throw new Error("recipient_not_selected");
  }

  const result = await admin
    .from("emergency_contacts")
    .select(
      "id,user_id,name,alias,email,target_user_id,approval_status,blocked,restricted",
    )
    .eq("id", params.recipientContactId)
    .eq("user_id", params.ownerUserId)
    .eq("approval_status", "approved")
    .maybeSingle();

  if (result.error) {
    logDatabaseFailure("selected contact lookup", result.error);
    throw new Error("recipient_lookup_failed");
  }

  const contact = result.data as ContactRow | null;

  if (!contact || contact.blocked === true || contact.restricted === true) {
    throw new Error("recipient_not_authorized");
  }

  return contact;
}

async function resolveResponderUserId(
  admin: SupabaseClient,
  contact: ContactRow,
): Promise<string> {
  const targetUserId = clean(contact.target_user_id);

  if (isUuid(targetUserId)) {
    return targetUserId;
  }

  const resolved = await resolveStayKnownUserByEmail(
    admin,
    clean(contact.email),
  );

  return isUuid(resolved) ? resolved : "";
}

async function validateConsent(
  admin: SupabaseClient,
  params: {
    consentId: string;
    visitId: string;
    ownerUserId: string;
    recipientContactId: string;
    audience: string;
    signedVersion: string;
    signedExpiry: number;
  },
): Promise<void> {
  if (!isUuid(params.consentId)) {
    throw new Error("consent_required");
  }

  const result = await admin
    .from("visit_map_access_consents")
    .select(
      "id,decision,policy_version,owner_user_id,recipient_contact_id,audience,signed_exp,signed_version",
    )
    .eq("id", params.consentId)
    .eq("visit_id", params.visitId)
    .eq("owner_user_id", params.ownerUserId)
    .eq("recipient_contact_id", params.recipientContactId)
    .eq("decision", "accepted")
    .eq("policy_version", POLICY_VERSION)
    .maybeSingle();

  if (result.error) {
    logDatabaseFailure("LIVE consent lookup", result.error);
    throw new Error("consent_lookup_failed");
  }

  const row = asObject(result.data);

  const matches =
    Boolean(result.data) &&
    clean(row.audience) === params.audience &&
    clean(row.signed_version) === params.signedVersion &&
    Number(row.signed_exp) === params.signedExpiry;

  if (!matches) {
    throw new Error("consent_required");
  }
}

function rpcFailureCode(error: unknown): string {
  const message = clean(asObject(error).message).toLowerCase();

  if (
    message.includes("not attached") ||
    message.includes("cannot respond as their own contact")
  ) {
    return "recipient_not_authorized";
  }

  if (
    message.includes("timing record not found") ||
    message.includes("deadline alert was not found") ||
    message.includes("alert was not found")
  ) {
    return "response_opportunity_closed";
  }

  if (
    message.includes("invalid deadline") ||
    message.includes("invalid visit time response")
  ) {
    return "invalid_response_request";
  }

  return backendObjectMissing(error)
    ? "response_authority_unavailable"
    : "response_record_failed";
}

async function recordAuthoritativeResponse(
  admin: SupabaseClient,
  params: {
    visitId: string;
    deadlineVersion: number;
    responder: ResponderIdentity;
    recipientContactId: string;
    responseKind: LiveResponseAction;
    consentId: string;
    responseOpportunityId: string;
    req: Request;
  },
): Promise<RpcEnvelope> {
  const result = await admin.rpc("sk_upsert_visit_time_contact_response", {
    p_visit_id: params.visitId,
    p_deadline_version: params.deadlineVersion,
    p_responder_user_id: params.responder.userId,
    p_recipient_contact_id: params.recipientContactId,
    p_response_kind: params.responseKind,
    p_source_notification_id: null,
    p_metadata: {
      source: "signed_live_map",
      authority: "sk_upsert_visit_time_contact_response",
      surface: "live_map_website",
      consent_id: params.consentId,
      response_opportunity_id: params.responseOpportunityId,
      response_profile: RESPONSE_PROFILE,
      responder_name: params.responder.displayName,
      responder_email: params.responder.email,
      responder_avatar_url: params.responder.avatarUrl,
      responder_verified: params.responder.verified,
      responder_badge_type: params.responder.badgeType || null,
      responder_badge_status: params.responder.badgeStatus || null,
      action_received_at: new Date().toISOString(),
      ip_hash: requestIpHash(params.req) || null,
      client: userAgentSummary(params.req),
      raw_signed_access_stored: false,
      raw_ip_address_stored: false,
      raw_user_agent_stored: false,
      exact_coordinates_stored: false,
      device_identifier_stored: false,
      account_credentials_stored: false,
      modifies_visit: false,
      changes_visit_deadline: false,
      ends_visit: false,
      starts_sos: false,
      stops_sos: false,
      contacts_emergency_services: false,
      proves_safety: false,
    },
  });

  if (result.error) {
    logDatabaseFailure("authoritative Visit-time response RPC", result.error);

    throw new Error(rpcFailureCode(result.error));
  }

  const envelope = asObject(result.data) as RpcEnvelope;

  if (envelope.ok === false) {
    throw new Error("response_record_failed");
  }

  return envelope;
}

async function upsertOwnerNotification(
  admin: SupabaseClient,
  params: {
    ownerUserId: string;
    visitId: string;
    deadlineVersion: number;
    responder: ResponderIdentity;
    contactId: string;
    responseKind: LiveResponseAction;
    responseId: string;
    copy: ResponseCopy;
  },
): Promise<string> {
  const dedupeKey =
    `visit_time_response:${params.visitId}:` +
    `${params.deadlineVersion}:` +
    `${params.responder.userId}:` +
    `${params.responseKind}`;

  const data: JsonObject = {
    source: "respond_visit_time_contact",
    event: "visit_time_contact_response",
    audience: "owner",
    visit_id: params.visitId,
    session_id: params.visitId,
    deadline_version: params.deadlineVersion,
    responder_user_id: params.responder.userId,
    responder_name: params.responder.displayName,
    responder_avatar_url: params.responder.avatarUrl,
    responder_verified: params.responder.verified,
    responder_badge_type: params.responder.badgeType,
    responder_badge_status: params.responder.badgeStatus,
    recipient_contact_id: params.contactId,
    response_id: params.responseId || null,
    response_kind: params.responseKind,
    severity: params.copy.severity,
    notification_action_set: "none",
    stop_critical_sound: true,
    deep_link: `stayknown://visit-time?visit_id=${encodeURIComponent(
      params.visitId,
    )}`,
    persistent_in_app: true,
    dedupe_key: dedupeKey,
    response_is_reported_evidence: true,
    response_proves_safety: false,
  };

  const result = await admin
    .from("notifications")
    .upsert(
      {
        user_id: params.ownerUserId,
        title: params.copy.title,
        body: params.copy.body,
        kind: params.copy.notificationKind,
        data,
        meta: {
          source: "respond_visit_time_contact",
          event: "visit_time_contact_response",
          audience: "owner",
          visit_id: params.visitId,
          deadline_version: params.deadlineVersion,
          response_kind: params.responseKind,
          severity: params.copy.severity,
          persistent_in_app: true,
          dedupe_key: dedupeKey,
          response_is_reported_evidence: true,
          response_proves_safety: false,
          updated_at: new Date().toISOString(),
        },
        dedupe_key: dedupeKey,
      },
      {
        onConflict: "user_id,dedupe_key",
      },
    )
    .select("id")
    .single();

  if (result.error) {
    logDatabaseFailure("owner notification upsert", result.error);
    return "";
  }

  return clean(result.data?.id);
}

function abortAfter(milliseconds: number): {
  signal: AbortSignal;
  cancel: () => void;
} {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), milliseconds);

  return {
    signal: controller.signal,
    cancel: () => clearTimeout(timer),
  };
}

async function sendOwnerPush(params: {
  ownerUserId: string;
  notificationId: string;
  visitId: string;
  deadlineVersion: number;
  responder: ResponderIdentity;
  contactId: string;
  responseId: string;
  responseKind: LiveResponseAction;
  copy: ResponseCopy;
}): Promise<{ delivered: boolean; code: string }> {
  const supabaseUrl = clean(
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL,
  ).replace(/\/+$/g, "");

  const internalSecret = clean(process.env.INTERNAL_EVENT_SECRET);

  if (!supabaseUrl || !internalSecret) {
    return {
      delivered: false,
      code: "push_not_configured",
    };
  }

  const timeout = abortAfter(PUSH_TIMEOUT_MS);

  try {
    const response = await fetch(
      `${supabaseUrl}/functions/v1/send_push_notification`,
      {
        method: "POST",
        cache: "no-store",
        signal: timeout.signal,
        headers: {
          "Content-Type": "application/json",
          "x-internal-event-secret": internalSecret,
        },
        body: JSON.stringify({
          user_id: params.ownerUserId,
          title: params.copy.title,
          body: params.copy.body,
          kind: params.copy.notificationKind,
          notification_id: params.notificationId || null,
          collapse_key: `visit_time_response_${params.visitId}`,
          thread_id: `visit_${params.visitId}`,
          ttl_seconds: 86400,
          data_only_android: true,
          data: {
            source: "respond_visit_time_contact",
            event: "visit_time_contact_response",
            audience: "owner",
            visit_id: params.visitId,
            session_id: params.visitId,
            deadline_version: params.deadlineVersion,
            responder_user_id: params.responder.userId,
            responder_name: params.responder.displayName,
            responder_avatar_url: params.responder.avatarUrl,
            responder_verified: params.responder.verified,
            responder_badge_type: params.responder.badgeType,
            responder_badge_status: params.responder.badgeStatus,
            recipient_contact_id: params.contactId,
            response_id: params.responseId || null,
            response_kind: params.responseKind,
            severity: params.copy.severity,
            notification_id: params.notificationId || null,
            notification_action_set: "none",
            stop_critical_sound: true,
            deep_link: `stayknown://visit-time?visit_id=${encodeURIComponent(
              params.visitId,
            )}`,
            response_is_reported_evidence: true,
            response_proves_safety: false,
          },
        }),
      },
    );

    return {
      delivered: response.ok,
      code: response.ok ? "delivered" : `push_http_${response.status}`,
    };
  } catch (error) {
    return {
      delivered: false,
      code:
        error instanceof Error && error.name === "AbortError"
          ? "push_timeout"
          : "push_failed",
    };
  } finally {
    timeout.cancel();
  }
}

async function writeTimelineEvent(
  admin: SupabaseClient,
  params: {
    ownerUserId: string;
    visitId: string;
    deadlineVersion: number;
    responder: ResponderIdentity;
    contactId: string;
    responseId: string;
    responseKind: LiveResponseAction;
    copy: ResponseCopy;
  },
): Promise<boolean> {
  const result = await admin.from("safety_timeline_events").insert({
    user_id: params.ownerUserId,
    event_type: "visit_time_contact_response",
    title: params.copy.title,
    body: params.copy.body,
    severity: params.copy.severity,
    source: "respond_visit_time_contact",
    related_kind: "visit",
    related_id: params.visitId,
    recipients_count: 1,
    meta: {
      response_id: params.responseId || null,
      deadline_version: params.deadlineVersion,
      responder_user_id: params.responder.userId,
      responder_name: params.responder.displayName,
      responder_avatar_url: params.responder.avatarUrl,
      responder_verified: params.responder.verified,
      responder_badge_type: params.responder.badgeType || null,
      responder_badge_status: params.responder.badgeStatus || null,
      recipient_contact_id: params.contactId,
      response_kind: params.responseKind,
      response_is_reported_evidence: true,
      response_proves_safety: false,
      modifies_visit: false,
      changes_visit_deadline: false,
      ends_visit: false,
      starts_sos: false,
      contacts_emergency_services: false,
    },
  });

  if (result.error) {
    logDatabaseFailure("timeline event insert", result.error);
    return false;
  }

  return true;
}

async function recordDeliveryHealth(
  admin: SupabaseClient,
  params: {
    ownerUserId: string;
    visitId: string;
    responderUserId: string;
    responseId: string;
    responseKind: LiveResponseAction;
    respondedAt: string;
    notificationRecorded: boolean;
    pushDelivered: boolean;
  },
): Promise<boolean> {
  const overallState =
    params.notificationRecorded && params.pushDelivered
      ? "delivered"
      : params.notificationRecorded || params.pushDelivered
        ? "partial"
        : "failed";

  try {
    const result = await admin.rpc("sk_upsert_safety_delivery_health", {
      p_owner_user_id: params.ownerUserId,
      p_flow_kind: "visit",
      p_related_id: params.visitId,
      p_source: "respond_visit_time_contact",
      p_health: {
        overall_state: overallState,
        delivery_confidence:
          overallState === "delivered"
            ? "high"
            : overallState === "partial"
              ? "medium"
              : "low",
        event: "visit_time_contact_response",
        response_id: params.responseId || null,
        response_kind: params.responseKind,
        responded_at: params.respondedAt,
        owner_notification_recorded: params.notificationRecorded,
        owner_push_delivered: params.pushDelivered,
        authority: {
          records_response: true,
          modifies_visit: false,
          changes_visit_deadline: false,
          ends_visit: false,
          starts_sos: false,
          contacts_emergency_services: false,
          proves_safety: false,
        },
      },
      p_viewer_user_ids: [params.ownerUserId, params.responderUserId],
    });

    if (result.error) {
      if (!backendObjectMissing(result.error)) {
        logDatabaseFailure("delivery-health projection", result.error);
      }

      return false;
    }

    return true;
  } catch (error) {
    if (!backendObjectMissing(error)) {
      logDatabaseFailure("delivery-health projection", error);
    }

    return false;
  }
}

async function requestLiveIntelligence(params: {
  ownerUserId: string;
  visitId: string;
  responseId: string;
  responseKind: LiveResponseAction;
  respondedAt: string;
}): Promise<boolean> {
  const supabaseUrl = clean(
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL,
  ).replace(/\/+$/g, "");

  const internalSecret = clean(process.env.INTERNAL_EVENT_SECRET);

  if (!supabaseUrl || !internalSecret) {
    return false;
  }

  const timeout = abortAfter(INTELLIGENCE_TIMEOUT_MS);

  try {
    const response = await fetch(
      `${supabaseUrl}/functions/v1/process_live_visit_intelligence`,
      {
        method: "POST",
        cache: "no-store",
        signal: timeout.signal,
        headers: {
          "Content-Type": "application/json",
          "x-internal-event-secret": internalSecret,
        },
        body: JSON.stringify({
          user_id: params.ownerUserId,
          visit_id: params.visitId,
          trigger: "visit_time_contact_response",
          client_observed_at: params.respondedAt,
          client_evidence: {
            response_id: params.responseId || null,
            response_kind: params.responseKind,
            source: "respond_visit_time_contact",
            authoritative_response: true,
            response_is_reported_evidence: true,
            response_proves_safety: false,
            modifies_visit: false,
            changes_visit_deadline: false,
            ends_visit: false,
            starts_sos: false,
            contacts_emergency_services: false,
          },
        }),
      },
    );

    return response.ok;
  } catch {
    return false;
  } finally {
    timeout.cancel();
  }
}

function deliveryHealth(projection: DeliveryProjection): LiveDeliveryHealth {
  if (projection.notificationRecorded && projection.pushDelivered) {
    return "healthy";
  }

  if (projection.notificationRecorded || projection.pushDelivered) {
    return "degraded";
  }

  return "offline";
}

function safeFailure(error: unknown): {
  status: number;
  code: string;
  message: string;
} {
  const code = error instanceof Error ? clean(error.message) : "";

  const failures: Record<string, { status: number; message: string }> = {
    invalid_response_request: {
      status: 400,
      message: "Choose Checking, Reached them or Can’t reach.",
    },
    invalid_response_profile: {
      status: 400,
      message: "This LIVE response profile is not supported.",
    },
    invalid_response_opportunity: {
      status: 403,
      message: "This LIVE response opportunity could not be verified.",
    },
    consent_required: {
      status: 403,
      message: "Accept the safety-use policy before recording a response.",
    },
    consent_lookup_failed: {
      status: 503,
      message: "StayKnown could not verify the recorded safety-use consent.",
    },
    recipient_not_selected: {
      status: 403,
      message:
        "This response is restricted to the approved contact selected for the Visit.",
    },
    recipient_not_authorized: {
      status: 403,
      message:
        "This recipient is not authorized to record this Visit response.",
    },
    recipient_lookup_failed: {
      status: 503,
      message: "StayKnown could not verify the selected contact right now.",
    },
    stayknown_account_required: {
      status: 403,
      message:
        "This response requires the selected contact’s StayKnown account.",
    },
    responder_is_owner: {
      status: 403,
      message: "The Visit owner cannot respond as their own selected contact.",
    },
    timing_not_found: {
      status: 404,
      message: "The Visit timing record is no longer available.",
    },
    timing_lookup_failed: {
      status: 503,
      message: "StayKnown could not verify the Visit timing right now.",
    },
    timing_subject_mismatch: {
      status: 403,
      message: "The Visit timing record does not match this signed LIVE Visit.",
    },
    timing_not_ready: {
      status: 409,
      message: "This Visit response opportunity is not ready yet.",
    },
    response_opportunity_not_open: {
      status: 409,
      message: "The expected Visit time has not been exceeded.",
    },
    response_opportunity_closed: {
      status: 409,
      message: "This Visit response opportunity has ended.",
    },
    response_authority_unavailable: {
      status: 503,
      message: "The authoritative Visit response service is not available yet.",
    },
    response_record_failed: {
      status: 503,
      message:
        "StayKnown could not safely record this Visit response right now.",
    },
    visit_not_found: {
      status: 404,
      message: "This LIVE Visit is no longer available.",
    },
    recipient_email_missing: {
      status: 403,
      message:
        "This recipient is not authorized to record this Visit response.",
    },
    visit_access_failed: {
      status: 503,
      message: "StayKnown could not verify this LIVE Visit right now.",
    },
    recipient_access_failed: {
      status: 503,
      message: "StayKnown could not verify this recipient right now.",
    },
    live_configuration_unavailable: {
      status: 503,
      message: "The secure LIVE Visit service is temporarily unavailable.",
    },
  };

  const known = failures[code];

  if (known) {
    return {
      status: known.status,
      code,
      message: known.message,
    };
  }

  return {
    status: 500,
    code: "live_response_failed",
    message:
      "StayKnown could not safely record this response. Please try again.",
  };
}

export async function POST(req: Request): Promise<NextResponse> {
  try {
    if (!contentTypeIsJson(req)) {
      return jsonResponse(
        {
          ok: false,
          code: "unsupported_content_type",
          error: "Submit this response from the protected StayKnown LIVE page.",
        },
        415,
      );
    }

    if (!requestIsSameOrigin(req)) {
      return jsonResponse(
        {
          ok: false,
          code: "invalid_request_origin",
          error:
            "This response must be submitted from the protected StayKnown LIVE page.",
        },
        403,
      );
    }

    const body = asObject(await req.json().catch(() => ({})));

    if (body.is_practice === true) {
      return jsonResponse(
        {
          ok: false,
          code: "practice_route_required",
          error:
            "Practice Mode responses must use the protected Practice Mode route.",
        },
        409,
      );
    }

    const access = accessFromUnknown(body);
    const verified = verifyLiveAccess(access);

    if (!verified.ok) {
      return jsonResponse(
        {
          ok: false,
          code: "invalid_live_access",
          error: "This signed LIVE Visit access is invalid or expired.",
        },
        401,
      );
    }

    const responseKind = normalizeResponseAction(
      body.response_kind ?? body.action ?? body.action_kind,
    );

    if (!responseKind) {
      throw new Error("invalid_response_request");
    }

    const responseProfile = clean(body.response_profile);

    if (responseProfile !== RESPONSE_PROFILE) {
      throw new Error("invalid_response_profile");
    }

    const submittedOpportunityId = clean(body.response_opportunity_id);

    if (!submittedOpportunityId) {
      throw new Error("invalid_response_opportunity");
    }

    const consentId = clean(body.consent_id);

    const admin = createAdminClient();
    const accessContext = await validateVisitAccess(admin, verified);

    if (!canUseInteractiveLiveActions(verified, accessContext)) {
      throw new Error("recipient_not_authorized");
    }

    if (visitHasEnded(accessContext.visit)) {
      throw new Error("response_opportunity_closed");
    }

    const recipient = accessContext.recipient;

    if (!recipient) {
      throw new Error("recipient_not_authorized");
    }

    const ownerUserId = visitOwnerUserId(accessContext, verified);

    const timing = await loadTiming(admin, verified.sid);

    const deadlineVersion = validateTiming({
      timing,
      visitId: verified.sid,
      ownerUserId,
      recipientContactId: recipient.id,
    });

    const expectedOpportunityId = opportunityId({
      visitId: verified.sid,
      recipientContactId: recipient.id,
      deadlineVersion,
    });

    if (!safeEqualText(submittedOpportunityId, expectedOpportunityId)) {
      throw new Error("invalid_response_opportunity");
    }

    await validateConsent(admin, {
      consentId,
      visitId: verified.sid,
      ownerUserId,
      recipientContactId: recipient.id,
      audience: verified.aud,
      signedVersion: verified.version,
      signedExpiry: verified.expNumber,
    });

    const selectedContactIds = asStringArray(timing.selected_contact_ids);

    const contact = await loadSelectedContact(admin, {
      ownerUserId,
      recipientContactId: recipient.id,
      selectedContactIds,
    });

    const responderUserId = await resolveResponderUserId(admin, contact);

    if (!responderUserId) {
      throw new Error("stayknown_account_required");
    }

    if (responderUserId === ownerUserId) {
      throw new Error("responder_is_owner");
    }

    const responder = await loadResponderIdentity(admin, {
      responderUserId,
      contact,
    });

    const rpc = await recordAuthoritativeResponse(admin, {
      visitId: verified.sid,
      deadlineVersion,
      responder,
      recipientContactId: recipient.id,
      responseKind,
      consentId,
      responseOpportunityId: submittedOpportunityId,
      req,
    });

    const changed = rpc.changed === true;
    const alreadyRecorded =
      rpc.already_recorded === true || (!changed && rpc.changed === false);

    const responseRow = asObject(rpc.response) as RpcResponse;

    const responseId = clean(responseRow.id);
    const respondedAt =
      clean(responseRow.responded_at) ||
      clean(responseRow.updated_at) ||
      new Date().toISOString();

    const copy = responseCopy(responseKind, responder.displayName);

    const delivery: DeliveryProjection = {
      notificationRecorded: false,
      pushDelivered: false,
      pushCode: changed ? "pending" : "unchanged_response",
      timelineRecorded: false,
      deliveryHealthRecorded: false,
      intelligenceRequested: false,
    };

    /*
    The RPC is authoritative. Delivery projections execute only when the
    response actually changed. Repeating the same action remains idempotent and
    does not create another notification, push, timeline event, or intelligence
    trigger.
    */
    if (changed) {
      const notificationId = await upsertOwnerNotification(admin, {
        ownerUserId,
        visitId: verified.sid,
        deadlineVersion,
        responder,
        contactId: recipient.id,
        responseKind,
        responseId,
        copy,
      });

      delivery.notificationRecorded = Boolean(notificationId);

      const push = await sendOwnerPush({
        ownerUserId,
        notificationId,
        visitId: verified.sid,
        deadlineVersion,
        responder,
        contactId: recipient.id,
        responseId,
        responseKind,
        copy,
      });

      delivery.pushDelivered = push.delivered;
      delivery.pushCode = push.code;

      delivery.timelineRecorded = await writeTimelineEvent(admin, {
        ownerUserId,
        visitId: verified.sid,
        deadlineVersion,
        responder,
        contactId: recipient.id,
        responseId,
        responseKind,
        copy,
      });

      delivery.deliveryHealthRecorded = await recordDeliveryHealth(admin, {
        ownerUserId,
        visitId: verified.sid,
        responderUserId,
        responseId,
        responseKind,
        respondedAt,
        notificationRecorded: delivery.notificationRecorded,
        pushDelivered: delivery.pushDelivered,
      });

      delivery.intelligenceRequested = await requestLiveIntelligence({
        ownerUserId,
        visitId: verified.sid,
        responseId,
        responseKind,
        respondedAt,
      });
    }

    const result: RouteSuccess = {
      ok: true,
      session_id: verified.sid,
      changed,
      already_recorded: alreadyRecorded,
      label: alreadyRecorded
        ? "Response already recorded"
        : `${copy.label} recorded`,
      message: alreadyRecorded
        ? "This response was already recorded."
        : copy.confirmation,
      authority: "sk_upsert_visit_time_contact_response",
      response_profile: RESPONSE_PROFILE,
      response: {
        id: responseId || null,
        action: responseKind,
        state: clean(responseRow.status) || "active",
        recorded_at: respondedAt,
        idempotent: alreadyRecorded,
      },
      delivery_health: changed ? deliveryHealth(delivery) : "healthy",
      delivery: {
        notification_recorded: delivery.notificationRecorded,
        push_delivered: delivery.pushDelivered,
        timeline_recorded: delivery.timelineRecorded,
      },
    };

    return jsonResponse(result);
  } catch (error) {
    console.error("[SK_LIVE_RESPONSE] request failed", {
      code: error instanceof Error ? clean(error.message) : "unknown_error",
    });

    const failure = safeFailure(error);

    return jsonResponse(
      {
        ok: false,
        code: failure.code,
        error: failure.message,
      },
      failure.status,
    );
  }
}
